import numpy as np
import numpy.random as np_random
def arrayRemodeling():
    print('将一维数组转换为二维数组')
    arr=np.arange(8)
    print(arr)
    print(arr.reshape((4,2)))
    print(arr.reshape((4,2)).reshape((2,4)))
    print('维度大小自动推导')
    arr=np.arange(15)
    print(arr)
    print(arr.reshape((5,-1)))
    print('获取维度信息并应用')
    other_arr=np.ones((3,5))
    print(other_arr)
    print(other_arr.shape)
    print(arr.reshape(other_arr.shape))
    print('高维数组推平')
    arr=np.arange(15).reshape((5,3))
    print(arr)
    print(arr.ravel())
    print('----------------------------------')
    print('链接两个二位数组')
    arr1=np.array([[1,2,3],[4,5,6]])
    arr2=np.array([[7,8,9],[10,11,12]])
    print('按行链接')
    print(np.concatenate([arr1,arr2],axis=0))
    print('按列链接')
    print(np.concatenate([arr1,arr2],axis=1))
    print('垂直stack，水平stack')
    print('垂直堆叠')
    print(np.vstack((arr1,arr2)))
    print('水平堆叠')
    print(np.hstack((arr1,arr2)))
    print('拆分数组')
    arr=np_random.randn(5,5)
    print(arr)
    print('水平拆分')
    first,second,third=np.split(arr,[1,3],axis=0)
    print('first=',first)
    print('second=',second)
    print('third=',third)
    print('垂直拆分')
    first, second,third = np.split(arr, [1, 3], axis=1)
    print('first=', first)
    print('second=', second)
    print('third=', third)